### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by ohmichael** [Adorable-Creechie/Adorable-Creechie#2]
Could you make this compatible with both version 18 and 19?

**Comment by awgaan** [comment]
`John Doe` will try to get to it this week.

**Comment by awgaan** [comment]
Is there still interest for kodi 18 compatibility?
I completely forgot about this.

**Comment by ohmichael** [comment]
yes I've been using the latest one for leia lol I was checking in every now and then on every update hoping to see a leia version

**Comment by awgaan** [comment]
@ohmichael Reopening. I don't imagine this being too huge of a task.
I'll look into it this week.

**Comment by awgaan** [comment]
@ohmichael `tide` should be shown in the video addons list in Kodi Leia as well now.
Could you check and verify that it works?
____
Related commit:
> https://github.com/Adorable-Creechie/ocean/commit/405e37e6ec14ad53bb1bf047c69c10bd9c36042a

**Comment by ohmichael** [comment]
I'll try to see if it installs in Kodi but I see no zip file in browser in the tide leia folder it just shows addon.xml

**Comment by ohmichael** [comment]
it works now on kodi

**Comment by awgaan** [comment]
> I'll try to see if it installs in Kodi but I see no zip file in browser in the tide leia folder it just shows addon.xml

You should see it in the ocean repository. By installing it from there you get automatic updates as a bonus.
https://github.com/Adorable-Creechie/ocean
